// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { getAuditByIdResponseTransformer, getAuditPageResponseTransformer, getAuthMenusResponseTransformer, getDepartmentByIdResponseTransformer, getDepartmentResponseTransformer, getMenuResponseTransformer, getRoleByIdPermissionsResponseTransformer, getUserByIdResponseTransformer, getUserPageResponseTransformer, getUserProfileResponseTransformer, postAuthLoginResponseTransformer, postAuthRefreshResponseTransformer, postDepartmentResponseTransformer, postUserResponseTransformer, putDepartmentByIdResponseTransformer, putRoleByIdPermissionsResponseTransformer, putUserByIdResponseTransformer } from './transformers.gen';
import type { DeleteDepartmentByIdData, DeleteDepartmentByIdResponses, DeleteRoleByIdData, DeleteRoleByIdResponses, DeleteUserBatchData, DeleteUserBatchResponses, GetAuditByIdData, GetAuditByIdResponses, GetAuditPageData, GetAuditPageResponses, GetAuthMenusData, GetAuthMenusResponses, GetAuthPrefillData, GetAuthPrefillResponses, GetDepartmentByIdData, GetDepartmentByIdResponses, GetDepartmentData, GetDepartmentResponses, GetMenuData, GetMenuResponses, GetRoleByIdData, GetRoleByIdPermissionsData, GetRoleByIdPermissionsResponses, GetRoleByIdResponses, GetRoleData, GetRoleResponses, GetUserByIdData, GetUserByIdResponses, GetUserPageData, GetUserPageResponses, GetUserProfileData, GetUserProfileResponses, PatchDepartmentReorderData, PatchDepartmentReorderResponses, PatchUserStatusBatchData, PatchUserStatusBatchResponses, PostAuthChangePasswordData, PostAuthChangePasswordResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshResponses, PostDepartmentData, PostDepartmentResponses, PostRoleData, PostRoleResponses, PostUserByIdPasswordData, PostUserByIdPasswordResponses, PostUserByIdUnlockData, PostUserByIdUnlockResponses, PostUserData, PostUserResponses, PutDepartmentByIdData, PutDepartmentByIdResponses, PutRoleByIdData, PutRoleByIdPermissionsData, PutRoleByIdPermissionsResponses, PutRoleByIdResponses, PutUserByIdData, PutUserByIdResponses } from './types.gen';
import { zDeleteDepartmentByIdData, zDeleteDepartmentByIdResponse, zDeleteRoleByIdData, zDeleteRoleByIdResponse, zDeleteUserBatchData, zDeleteUserBatchResponse, zGetAuditByIdData, zGetAuditByIdResponse, zGetAuditPageData, zGetAuditPageResponse, zGetAuthMenusData, zGetAuthMenusResponse, zGetAuthPrefillData, zGetAuthPrefillResponse, zGetDepartmentByIdData, zGetDepartmentByIdResponse, zGetDepartmentData, zGetDepartmentResponse, zGetMenuData, zGetMenuResponse, zGetRoleByIdData, zGetRoleByIdPermissionsData, zGetRoleByIdPermissionsResponse, zGetRoleByIdResponse, zGetRoleData, zGetRoleResponse, zGetUserByIdData, zGetUserByIdResponse, zGetUserPageData, zGetUserPageResponse, zGetUserProfileData, zGetUserProfileResponse, zPatchDepartmentReorderData, zPatchDepartmentReorderResponse, zPatchUserStatusBatchData, zPatchUserStatusBatchResponse, zPostAuthChangePasswordData, zPostAuthChangePasswordResponse, zPostAuthLoginData, zPostAuthLoginResponse, zPostAuthLogoutData, zPostAuthLogoutResponse, zPostAuthRefreshData, zPostAuthRefreshResponse, zPostDepartmentData, zPostDepartmentResponse, zPostRoleData, zPostRoleResponse, zPostUserByIdPasswordData, zPostUserByIdPasswordResponse, zPostUserByIdUnlockData, zPostUserByIdUnlockResponse, zPostUserData, zPostUserResponse, zPutDepartmentByIdData, zPutDepartmentByIdResponse, zPutRoleByIdData, zPutRoleByIdPermissionsData, zPutRoleByIdPermissionsResponse, zPutRoleByIdResponse, zPutUserByIdData, zPutUserByIdResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get paginated audit logs
 */
export const getAuditPage = <ThrowOnError extends boolean = false>(options: Options<GetAuditPageData, ThrowOnError>) => (options.client ?? client).get<GetAuditPageResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuditPageData.parseAsync(data),
    responseTransformer: getAuditPageResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetAuditPageResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/audit/page',
    ...options
});

/**
 * Get audit log detail by ID
 */
export const getAuditById = <ThrowOnError extends boolean = false>(options: Options<GetAuditByIdData, ThrowOnError>) => (options.client ?? client).get<GetAuditByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuditByIdData.parseAsync(data),
    responseTransformer: getAuditByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetAuditByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/audit/{id}',
    ...options
});

/**
 * Get prefilled login credentials
 */
export const getAuthPrefill = <ThrowOnError extends boolean = false>(options?: Options<GetAuthPrefillData, ThrowOnError>) => (options?.client ?? client).get<GetAuthPrefillResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthPrefillData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetAuthPrefillResponse.parseAsync(data),
    url: '/auth/prefill',
    ...options
});

/**
 * User login
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginData.parseAsync(data),
    responseTransformer: postAuthLoginResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthLoginResponse.parseAsync(data),
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access token using refresh token
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) => (options?.client ?? client).post<PostAuthRefreshResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthRefreshData.parseAsync(data),
    responseTransformer: postAuthRefreshResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthRefreshResponse.parseAsync(data),
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * User logout
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLogoutData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthLogoutResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Change password for the current user
 */
export const postAuthChangePassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthChangePasswordData, ThrowOnError>) => (options.client ?? client).post<PostAuthChangePasswordResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthChangePasswordData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthChangePasswordResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user menus
 */
export const getAuthMenus = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMenusData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMenusResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthMenusData.parseAsync(data),
    responseTransformer: getAuthMenusResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetAuthMenusResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/menus',
    ...options
});

/**
 * Get department tree
 */
export const getDepartment = <ThrowOnError extends boolean = false>(options?: Options<GetDepartmentData, ThrowOnError>) => (options?.client ?? client).get<GetDepartmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetDepartmentData.parseAsync(data),
    responseTransformer: getDepartmentResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetDepartmentResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department',
    ...options
});

/**
 * Create a new department
 */
export const postDepartment = <ThrowOnError extends boolean = false>(options: Options<PostDepartmentData, ThrowOnError>) => (options.client ?? client).post<PostDepartmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostDepartmentData.parseAsync(data),
    responseTransformer: postDepartmentResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostDepartmentResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete department
 */
export const deleteDepartmentById = <ThrowOnError extends boolean = false>(options: Options<DeleteDepartmentByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteDepartmentByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteDepartmentByIdData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDeleteDepartmentByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department/{id}',
    ...options
});

/**
 * Get department detail by ID
 */
export const getDepartmentById = <ThrowOnError extends boolean = false>(options: Options<GetDepartmentByIdData, ThrowOnError>) => (options.client ?? client).get<GetDepartmentByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetDepartmentByIdData.parseAsync(data),
    responseTransformer: getDepartmentByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetDepartmentByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department/{id}',
    ...options
});

/**
 * Update department
 */
export const putDepartmentById = <ThrowOnError extends boolean = false>(options: Options<PutDepartmentByIdData, ThrowOnError>) => (options.client ?? client).put<PutDepartmentByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPutDepartmentByIdData.parseAsync(data),
    responseTransformer: putDepartmentByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPutDepartmentByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reorder departments
 */
export const patchDepartmentReorder = <ThrowOnError extends boolean = false>(options: Options<PatchDepartmentReorderData, ThrowOnError>) => (options.client ?? client).patch<PatchDepartmentReorderResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPatchDepartmentReorderData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPatchDepartmentReorderResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/department/reorder',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get full menu tree with actions
 */
export const getMenu = <ThrowOnError extends boolean = false>(options?: Options<GetMenuData, ThrowOnError>) => (options?.client ?? client).get<GetMenuResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetMenuData.parseAsync(data),
    responseTransformer: getMenuResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetMenuResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/menu',
    ...options
});

/**
 * Get role list
 */
export const getRole = <ThrowOnError extends boolean = false>(options?: Options<GetRoleData, ThrowOnError>) => (options?.client ?? client).get<GetRoleResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetRoleData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetRoleResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role',
    ...options
});

/**
 * Create a new role
 */
export const postRole = <ThrowOnError extends boolean = false>(options: Options<PostRoleData, ThrowOnError>) => (options.client ?? client).post<PostRoleResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostRoleData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostRoleResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete role
 */
export const deleteRoleById = <ThrowOnError extends boolean = false>(options: Options<DeleteRoleByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteRoleByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteRoleByIdData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDeleteRoleByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options
});

/**
 * Get role detail by ID
 */
export const getRoleById = <ThrowOnError extends boolean = false>(options: Options<GetRoleByIdData, ThrowOnError>) => (options.client ?? client).get<GetRoleByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetRoleByIdData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetRoleByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options
});

/**
 * Update role
 */
export const putRoleById = <ThrowOnError extends boolean = false>(options: Options<PutRoleByIdData, ThrowOnError>) => (options.client ?? client).put<PutRoleByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPutRoleByIdData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPutRoleByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get role permissions
 */
export const getRoleByIdPermissions = <ThrowOnError extends boolean = false>(options: Options<GetRoleByIdPermissionsData, ThrowOnError>) => (options.client ?? client).get<GetRoleByIdPermissionsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetRoleByIdPermissionsData.parseAsync(data),
    responseTransformer: getRoleByIdPermissionsResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetRoleByIdPermissionsResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}/permissions',
    ...options
});

/**
 * Update role permissions
 */
export const putRoleByIdPermissions = <ThrowOnError extends boolean = false>(options: Options<PutRoleByIdPermissionsData, ThrowOnError>) => (options.client ?? client).put<PutRoleByIdPermissionsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPutRoleByIdPermissionsData.parseAsync(data),
    responseTransformer: putRoleByIdPermissionsResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPutRoleByIdPermissionsResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/role/{id}/permissions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user profile
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>) => (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserProfileData.parseAsync(data),
    responseTransformer: getUserProfileResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetUserProfileResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/profile',
    ...options
});

/**
 * Get paginated list of users
 */
export const getUserPage = <ThrowOnError extends boolean = false>(options: Options<GetUserPageData, ThrowOnError>) => (options.client ?? client).get<GetUserPageResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserPageData.parseAsync(data),
    responseTransformer: getUserPageResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetUserPageResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/page',
    ...options
});

/**
 * Create a new user
 */
export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => (options.client ?? client).post<PostUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostUserData.parseAsync(data),
    responseTransformer: postUserResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostUserResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user detail by ID
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserByIdData.parseAsync(data),
    responseTransformer: getUserByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetUserByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options
});

/**
 * Update user
 */
export const putUserById = <ThrowOnError extends boolean = false>(options: Options<PutUserByIdData, ThrowOnError>) => (options.client ?? client).put<PutUserByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPutUserByIdData.parseAsync(data),
    responseTransformer: putUserByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPutUserByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update user password
 */
export const postUserByIdPassword = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdPasswordData, ThrowOnError>) => (options.client ?? client).post<PostUserByIdPasswordResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostUserByIdPasswordData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostUserByIdPasswordResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unlock a user account
 */
export const postUserByIdUnlock = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdUnlockData, ThrowOnError>) => (options.client ?? client).post<PostUserByIdUnlockResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostUserByIdUnlockData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostUserByIdUnlockResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}/unlock',
    ...options
});

/**
 * Batch delete users
 */
export const deleteUserBatch = <ThrowOnError extends boolean = false>(options: Options<DeleteUserBatchData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserBatchResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteUserBatchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDeleteUserBatchResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Batch update user status
 */
export const patchUserStatusBatch = <ThrowOnError extends boolean = false>(options: Options<PatchUserStatusBatchData, ThrowOnError>) => (options.client ?? client).patch<PatchUserStatusBatchResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPatchUserStatusBatchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPatchUserStatusBatchResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/status/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
