// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { getAuthMenusResponseTransformer, getUserPageResponseTransformer, getUserProfileResponseTransformer, postAuthLoginResponseTransformer, postAuthRefreshResponseTransformer, postUserResponseTransformer, putUserByIdResponseTransformer } from './transformers.gen';
import type { DeleteUserBatchData, DeleteUserBatchResponses, GetAuthMenusData, GetAuthMenusResponses, GetAuthPrefillData, GetAuthPrefillResponses, GetUserPageData, GetUserPageResponses, GetUserProfileData, GetUserProfileResponses, PatchUserStatusBatchData, PatchUserStatusBatchResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshResponses, PostUserData, PostUserResponses, PutUserByIdData, PutUserByIdResponses } from './types.gen';
import { zDeleteUserBatchData, zDeleteUserBatchResponse, zGetAuthMenusData, zGetAuthMenusResponse, zGetAuthPrefillData, zGetAuthPrefillResponse, zGetUserPageData, zGetUserPageResponse, zGetUserProfileData, zGetUserProfileResponse, zPatchUserStatusBatchData, zPatchUserStatusBatchResponse, zPostAuthLoginData, zPostAuthLoginResponse, zPostAuthLogoutData, zPostAuthLogoutResponse, zPostAuthRefreshData, zPostAuthRefreshResponse, zPostUserData, zPostUserResponse, zPutUserByIdData, zPutUserByIdResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get prefilled login credentials
 */
export const getAuthPrefill = <ThrowOnError extends boolean = false>(options?: Options<GetAuthPrefillData, ThrowOnError>) => (options?.client ?? client).get<GetAuthPrefillResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthPrefillData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetAuthPrefillResponse.parseAsync(data),
    url: '/auth/prefill',
    ...options
});

/**
 * User login
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginData.parseAsync(data),
    responseTransformer: postAuthLoginResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthLoginResponse.parseAsync(data),
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh access token using refresh token
 */
export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>) => (options?.client ?? client).post<PostAuthRefreshResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthRefreshData.parseAsync(data),
    responseTransformer: postAuthRefreshResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthRefreshResponse.parseAsync(data),
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * User logout
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLogoutData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPostAuthLogoutResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Get user menus
 */
export const getAuthMenus = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMenusData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMenusResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthMenusData.parseAsync(data),
    responseTransformer: getAuthMenusResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetAuthMenusResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/menus',
    ...options
});

/**
 * Get user profile
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>) => (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserProfileData.parseAsync(data),
    responseTransformer: getUserProfileResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetUserProfileResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/profile',
    ...options
});

/**
 * Get paginated list of users
 */
export const getUserPage = <ThrowOnError extends boolean = false>(options: Options<GetUserPageData, ThrowOnError>) => (options.client ?? client).get<GetUserPageResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUserPageData.parseAsync(data),
    responseTransformer: getUserPageResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zGetUserPageResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/page',
    ...options
});

/**
 * Create a new user
 */
export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => (options.client ?? client).post<PostUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostUserData.parseAsync(data),
    responseTransformer: postUserResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPostUserResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update user
 */
export const putUserById = <ThrowOnError extends boolean = false>(options: Options<PutUserByIdData, ThrowOnError>) => (options.client ?? client).put<PutUserByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPutUserByIdData.parseAsync(data),
    responseTransformer: putUserByIdResponseTransformer,
    responseType: 'json',
    responseValidator: async (data) => await zPutUserByIdResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Batch delete users
 */
export const deleteUserBatch = <ThrowOnError extends boolean = false>(options: Options<DeleteUserBatchData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserBatchResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeleteUserBatchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDeleteUserBatchResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Batch update user status
 */
export const patchUserStatusBatch = <ThrowOnError extends boolean = false>(options: Options<PatchUserStatusBatchData, ThrowOnError>) => (options.client ?? client).patch<PatchUserStatusBatchResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPatchUserStatusBatchData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zPatchUserStatusBatchResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/status/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
