// This file is auto-generated by @hey-api/openapi-ts

import type { GetUserProfileResponse, PostAuthLoginResponse, PostAuthRefreshResponse, PostUserResponse } from './types.gen';

export const postAuthLoginResponseTransformer = async (data: any): Promise<PostAuthLoginResponse> => {
    data.refreshTokenExpiresAt = new Date(data.refreshTokenExpiresAt);
    return data;
};

export const postAuthRefreshResponseTransformer = async (data: any): Promise<PostAuthRefreshResponse> => {
    data.refreshTokenExpiresAt = new Date(data.refreshTokenExpiresAt);
    return data;
};

export const postUserResponseTransformer = async (data: any): Promise<PostUserResponse> => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};
