// This file is auto-generated by @hey-api/openapi-ts

import type { GetAuditByIdResponse, GetAuditPageResponse, GetAuthMenusResponse, GetDepartmentByIdResponse, GetDepartmentResponse, GetMenuResponse, GetRoleByIdPermissionsResponse, GetSystemDictItemsByIdResponse, GetSystemDictItemsPageResponse, GetSystemDictTypesByIdResponse, GetSystemDictTypesPageResponse, GetUserByIdResponse, GetUserPageResponse, GetUserProfileResponse, PostAuthLoginResponse, PostAuthRefreshResponse, PostDepartmentResponse, PostSystemDictItemsResponse, PostSystemDictTypesResponse, PostUserResponse, PutDepartmentByIdResponse, PutRoleByIdPermissionsResponse, PutSystemDictItemsByIdResponse, PutSystemDictTypesByIdResponse, PutUserByIdResponse } from './types.gen';

const auditLogListItemSchemaSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getAuditPageResponseTransformer = async (data: any): Promise<GetAuditPageResponse> => {
    data.items = data.items.map((item: any) => auditLogListItemSchemaSchemaResponseTransformer(item));
    return data;
};

const auditLogDetailResponseSchemaSchemaResponseTransformer = (data: any) => {
    data = auditLogListItemSchemaSchemaResponseTransformer(data);
    return data;
};

export const getAuditByIdResponseTransformer = async (data: any): Promise<GetAuditByIdResponse> => {
    data = auditLogDetailResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const postAuthLoginResponseTransformer = async (data: any): Promise<PostAuthLoginResponse> => {
    data.refreshTokenExpiresAt = new Date(data.refreshTokenExpiresAt);
    return data;
};

export const postAuthRefreshResponseTransformer = async (data: any): Promise<PostAuthRefreshResponse> => {
    data.refreshTokenExpiresAt = new Date(data.refreshTokenExpiresAt);
    return data;
};

const authMenuSchemaSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => authMenuSchemaSchemaResponseTransformer(item));
    return data;
};

export const getAuthMenusResponseTransformer = async (data: any): Promise<GetAuthMenusResponse> => {
    data = data.map((item: any) => authMenuSchemaSchemaResponseTransformer(item));
    return data;
};

const departmentProfileResponseSchemaSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const departmentTreeItemSchemaSchemaResponseTransformer = (data: any) => {
    data = departmentProfileResponseSchemaSchemaResponseTransformer(data);
    data.children = data.children.map((item: any) => departmentTreeItemSchemaSchemaResponseTransformer(item));
    return data;
};

const departmentTreeResponseSchemaSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => departmentTreeItemSchemaSchemaResponseTransformer(item));
    return data;
};

export const getDepartmentResponseTransformer = async (data: any): Promise<GetDepartmentResponse> => {
    data = departmentTreeResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const postDepartmentResponseTransformer = async (data: any): Promise<PostDepartmentResponse> => {
    data = departmentProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const getDepartmentByIdResponseTransformer = async (data: any): Promise<GetDepartmentByIdResponse> => {
    data = departmentProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const putDepartmentByIdResponseTransformer = async (data: any): Promise<PutDepartmentByIdResponse> => {
    data = departmentProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const menuItemSchemaSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => menuItemSchemaSchemaResponseTransformer(item));
    return data;
};

const menuTreeResponseSchemaSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => menuItemSchemaSchemaResponseTransformer(item));
    return data;
};

export const getMenuResponseTransformer = async (data: any): Promise<GetMenuResponse> => {
    data = menuTreeResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const rolePermissionTreeNodeSchemaSchemaResponseTransformer = (data: any) => {
    data.children = data.children.map((item: any) => rolePermissionTreeNodeSchemaSchemaResponseTransformer(item));
    return data;
};

const rolePermissionsResponseSchemaSchemaResponseTransformer = (data: any) => {
    data = data.map((item: any) => rolePermissionTreeNodeSchemaSchemaResponseTransformer(item));
    return data;
};

export const getRoleByIdPermissionsResponseTransformer = async (data: any): Promise<GetRoleByIdPermissionsResponse> => {
    data = rolePermissionsResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const putRoleByIdPermissionsResponseTransformer = async (data: any): Promise<PutRoleByIdPermissionsResponse> => {
    data = rolePermissionsResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const dictTypeResponseSchemaSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getSystemDictTypesPageResponseTransformer = async (data: any): Promise<GetSystemDictTypesPageResponse> => {
    data.items = data.items.map((item: any) => dictTypeResponseSchemaSchemaResponseTransformer(item));
    return data;
};

export const postSystemDictTypesResponseTransformer = async (data: any): Promise<PostSystemDictTypesResponse> => {
    data = dictTypeResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const getSystemDictTypesByIdResponseTransformer = async (data: any): Promise<GetSystemDictTypesByIdResponse> => {
    data = dictTypeResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const putSystemDictTypesByIdResponseTransformer = async (data: any): Promise<PutSystemDictTypesByIdResponse> => {
    data = dictTypeResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const dictItemResponseSchemaSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getSystemDictItemsPageResponseTransformer = async (data: any): Promise<GetSystemDictItemsPageResponse> => {
    data.items = data.items.map((item: any) => dictItemResponseSchemaSchemaResponseTransformer(item));
    return data;
};

export const postSystemDictItemsResponseTransformer = async (data: any): Promise<PostSystemDictItemsResponse> => {
    data = dictItemResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const getSystemDictItemsByIdResponseTransformer = async (data: any): Promise<GetSystemDictItemsByIdResponse> => {
    data = dictItemResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const putSystemDictItemsByIdResponseTransformer = async (data: any): Promise<PutSystemDictItemsByIdResponse> => {
    data = dictItemResponseSchemaSchemaResponseTransformer(data);
    return data;
};

const userProfileResponseSchemaSchemaResponseTransformer = (data: any) => {
    if (data.lockedUntil) {
        data.lockedUntil = new Date(data.lockedUntil);
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data = userProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const getUserPageResponseTransformer = async (data: any): Promise<GetUserPageResponse> => {
    data.items = data.items.map((item: any) => userProfileResponseSchemaSchemaResponseTransformer(item));
    return data;
};

export const postUserResponseTransformer = async (data: any): Promise<PostUserResponse> => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getUserByIdResponseTransformer = async (data: any): Promise<GetUserByIdResponse> => {
    data = userProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};

export const putUserByIdResponseTransformer = async (data: any): Promise<PutUserByIdResponse> => {
    data = userProfileResponseSchemaSchemaResponseTransformer(data);
    return data;
};
