// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        /**
         * Username of the user
         */
        username: string;
        /**
         * Password of the user
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * User logged in successfully
     */
    200: {
        /**
         * Access token for the user
         */
        accessToken: string;
        /**
         * Refresh token for the user
         */
        refreshToken: string;
        /**
         * Refresh token expiry duration
         */
        refreshTokenExpiresAt: string;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body?: {
        /**
         * Existing refresh token
         */
        refreshToken: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: {
        /**
         * New access token
         */
        accessToken: string;
        /**
         * Rotated refresh token
         */
        refreshToken: string;
        /**
         * New refresh token expiry duration
         */
        refreshTokenExpiresAt: string;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * User logged out successfully
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type PostUserData = {
    body?: {
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Password for the user
         */
        password: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
    };
    path?: never;
    query?: never;
    url: '/user';
};

export type PostUserResponses = {
    /**
     * User created successfully
     */
    201: {
        /**
         * Unique identifier for the user
         */
        id: string;
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
        /**
         * Timestamp when the user was created
         */
        createdAt: string;
        /**
         * Timestamp when the user was last updated
         */
        updatedAt: string;
    };
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];
