// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

/**
 * Standard error response envelope
 */
export type ErrorResponse = {
    code?: string;
    message: string;
    requestId: string;
};

export type AuthActionSchema = {
    /**
     * Action ID
     */
    id: string;
    /**
     * Action name
     */
    name: string;
};

export type AuthMenuSchema = {
    /**
     * Menu ID
     */
    id: string;
    /**
     * Menu name
     */
    name: string;
    /**
     * Menu path
     */
    path: string | null;
    /**
     * Child menus
     */
    children: Array<AuthMenuSchema>;
    /**
     * Menu actions
     */
    actions: Array<AuthActionSchema>;
};

export type GetAuthPrefillData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/prefill';
};

export type GetAuthPrefillResponses = {
    /**
     * Prefilled credentials retrieved successfully
     */
    200: {
        /**
         * Prefilled username for login form
         */
        username: string;
        /**
         * Prefilled password for login form
         */
        password: string;
    };
};

export type GetAuthPrefillResponse = GetAuthPrefillResponses[keyof GetAuthPrefillResponses];

export type PostAuthLoginData = {
    body: {
        /**
         * Username of the user
         */
        username: string;
        /**
         * Password of the user
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * User logged in successfully
     */
    200: {
        /**
         * Access token for the user
         */
        accessToken: string;
        /**
         * Refresh token for the user
         */
        refreshToken: string;
        /**
         * Refresh token expiry duration
         */
        refreshTokenExpiresAt: Date;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body?: {
        /**
         * Existing refresh token
         */
        refreshToken: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: {
        /**
         * New access token
         */
        accessToken: string;
        /**
         * Rotated refresh token
         */
        refreshToken: string;
        /**
         * New refresh token expiry duration
         */
        refreshTokenExpiresAt: Date;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * User logged out successfully
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMenusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/menus';
};

export type GetAuthMenusResponses = {
    /**
     * List of menus accessible to the user
     */
    200: Array<AuthMenuSchema>;
};

export type GetAuthMenusResponse = GetAuthMenusResponses[keyof GetAuthMenusResponses];

export type PostUserData = {
    body: {
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Password for the user
         */
        password: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
    };
    path?: never;
    query?: never;
    url: '/user';
};

export type PostUserResponses = {
    /**
     * User created successfully
     */
    201: {
        /**
         * Unique identifier for the user
         */
        id: string;
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
        /**
         * Timestamp when the user was created
         */
        createdAt: Date;
        /**
         * Timestamp when the user was last updated
         */
        updatedAt: Date;
    };
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type GetUserProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: {
        /**
         * Unique identifier for the user
         */
        id: string;
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
        /**
         * Status of the user account
         */
        status: 'ACTIVE' | 'DISABLED';
        /**
         * Timestamp when the user was created
         */
        createdAt: Date;
        /**
         * Timestamp when the user was last updated
         */
        updatedAt: Date;
    };
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type GetUserPageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
        /**
         * Sorting criteria in the format "field direction" or "field direction, field direction", e.g. "createdAt desc, username asc"
         */
        sort?: string | null;
        /**
         * Search term for filtering users by username, email, or display name
         */
        search?: string | null;
        /**
         * Filter users by account status
         */
        status?: 'ACTIVE' | 'DISABLED';
    };
    url: '/user/page';
};

export type GetUserPageResponses = {
    /**
     * Standard paginated response envelope
     */
    200: {
        /**
         * List of items for the current page
         */
        items: Array<{
            /**
             * Unique identifier for the user
             */
            id: string;
            /**
             * Unique username for the user
             */
            username: string;
            /**
             * Email address of the user
             */
            email: string | null;
            /**
             * Phone number of the user
             */
            phone: string | null;
            /**
             * Display name of the user
             */
            displayName: string | null;
            /**
             * Status of the user account
             */
            status: 'ACTIVE' | 'DISABLED';
            /**
             * Timestamp when the user was created
             */
            createdAt: Date;
            /**
             * Timestamp when the user was last updated
             */
            updatedAt: Date;
        }>;
        meta: {
            /**
             * Total number of items
             */
            total: number;
            /**
             * Current page number
             */
            page: number;
            /**
             * Number of items per page
             */
            pageSize: number;
            /**
             * Indicates if there is a next page
             */
            hasNext: boolean;
            /**
             * Indicates if there is a previous page
             */
            hasPrevious: boolean;
            /**
             * Sorting criteria used for the current page
             */
            sort: string | null;
        };
    };
};

export type GetUserPageResponse = GetUserPageResponses[keyof GetUserPageResponses];
