// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

/**
 * Standard error response envelope
 */
export type ErrorResponse = {
    code?: string;
    message: string;
    requestId: string;
};

export type AuthActionSchema = {
    /**
     * Action ID
     */
    id: string;
    /**
     * Action name
     */
    name: string;
};

export type AuthMenuSchema = {
    /**
     * Menu ID
     */
    id: string;
    /**
     * Menu name
     */
    name: string;
    /**
     * Menu path
     */
    path: string | null;
    /**
     * Child menus
     */
    children: Array<AuthMenuSchema>;
    /**
     * Menu actions
     */
    actions: Array<AuthActionSchema>;
};

export type RoleProfileResponseSchema = {
    /**
     * Unique identifier for the role
     */
    id: string;
    /**
     * Unique role name
     */
    name: string;
    /**
     * Role description
     */
    description: string | null;
};

export type RoleListResponseSchema = Array<RoleProfileResponseSchema>;

export type UserProfileResponseSchema = {
    /**
     * Unique identifier for the user
     */
    id: string;
    /**
     * Unique username for the user
     */
    username: string;
    /**
     * Role names assigned to the user
     */
    roles: Array<string>;
    /**
     * Email address of the user
     */
    email: string | null;
    /**
     * Phone number of the user
     */
    phone: string | null;
    /**
     * Display name of the user
     */
    displayName: string | null;
    /**
     * Status of the user account
     */
    status: 'ACTIVE' | 'DISABLED';
    /**
     * Timestamp when the user was created
     */
    createdAt: Date;
    /**
     * Timestamp when the user was last updated
     */
    updatedAt: Date;
};

export type PaginationMetaSchema = {
    /**
     * Total number of items
     */
    totalItem: number;
    /**
     * Total number of pages
     */
    totalPage: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    pageSize: number;
    /**
     * Next page number, null if current page is the last
     */
    nextPage: number | null;
    /**
     * Previous page number, null if current page is the first
     */
    previousPage: number | null;
    /**
     * Indicates if there is a next page
     */
    hasNext: boolean;
    /**
     * Indicates if there is a previous page
     */
    hasPrevious: boolean;
    /**
     * Sorting criteria used for the current page
     */
    sort: string | null;
};

export type GetAuthPrefillData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/prefill';
};

export type GetAuthPrefillResponses = {
    /**
     * Prefilled credentials retrieved successfully
     */
    200: {
        /**
         * Prefilled username for login form
         */
        username: string;
        /**
         * Prefilled password for login form
         */
        password: string;
    };
};

export type GetAuthPrefillResponse = GetAuthPrefillResponses[keyof GetAuthPrefillResponses];

export type PostAuthLoginData = {
    body: {
        /**
         * Username of the user
         */
        username: string;
        /**
         * Password of the user
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * User logged in successfully
     */
    200: {
        /**
         * Access token for the user
         */
        accessToken: string;
        /**
         * Refresh token for the user
         */
        refreshToken: string;
        /**
         * Refresh token expiry duration
         */
        refreshTokenExpiresAt: Date;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body?: {
        /**
         * Existing refresh token
         */
        refreshToken: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: {
        /**
         * New access token
         */
        accessToken: string;
        /**
         * Rotated refresh token
         */
        refreshToken: string;
        /**
         * New refresh token expiry duration
         */
        refreshTokenExpiresAt: Date;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * User logged out successfully
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMenusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/menus';
};

export type GetAuthMenusResponses = {
    /**
     * List of menus accessible to the user
     */
    200: Array<AuthMenuSchema>;
};

export type GetAuthMenusResponse = GetAuthMenusResponses[keyof GetAuthMenusResponses];

export type GetRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/role';
};

export type GetRoleResponses = {
    /**
     * Role list retrieved successfully
     */
    200: RoleListResponseSchema;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type PostRoleData = {
    body: {
        /**
         * Unique role name
         */
        name: string;
        /**
         * Role description
         */
        description: string | null;
    };
    path?: never;
    query?: never;
    url: '/role';
};

export type PostRoleResponses = {
    /**
     * Role created successfully
     */
    201: {
        /**
         * Unique identifier for the role
         */
        id: string;
        /**
         * Unique role name
         */
        name: string;
        /**
         * Role description
         */
        description: string | null;
    };
};

export type PostRoleResponse = PostRoleResponses[keyof PostRoleResponses];

export type DeleteRoleByIdData = {
    body?: never;
    path: {
        /**
         * Role ID
         */
        id: string;
    };
    query?: never;
    url: '/role/{id}';
};

export type DeleteRoleByIdResponses = {
    /**
     * Role deleted successfully
     */
    200: {
        /**
         * Number of roles deleted
         */
        deletedCount: number;
    };
};

export type DeleteRoleByIdResponse = DeleteRoleByIdResponses[keyof DeleteRoleByIdResponses];

export type GetRoleByIdData = {
    body?: never;
    path: {
        /**
         * Role ID
         */
        id: string;
    };
    query?: never;
    url: '/role/{id}';
};

export type GetRoleByIdResponses = {
    /**
     * Role detail retrieved successfully
     */
    200: RoleProfileResponseSchema;
};

export type GetRoleByIdResponse = GetRoleByIdResponses[keyof GetRoleByIdResponses];

export type PutRoleByIdData = {
    body: {
        /**
         * Unique role name
         */
        name?: string;
        /**
         * Role description
         */
        description?: string | null;
    };
    path: {
        /**
         * Role ID
         */
        id: string;
    };
    query?: never;
    url: '/role/{id}';
};

export type PutRoleByIdResponses = {
    /**
     * Role updated successfully
     */
    200: RoleProfileResponseSchema;
};

export type PutRoleByIdResponse = PutRoleByIdResponses[keyof PutRoleByIdResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type GetUserProfileResponses = {
    /**
     * User profile retrieved successfully
     */
    200: UserProfileResponseSchema;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type GetUserPageData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number for pagination
         */
        page: number;
        /**
         * Number of items per page
         */
        pageSize: number;
        /**
         * Sorting criteria in the format "field direction" or "field direction, field direction", e.g. "createdAt desc, username asc"
         */
        sort?: string | null;
        /**
         * Search term for filtering users by username, email, or display name
         */
        search?: string | null;
        /**
         * Filter users by one or more account statuses
         */
        status?: Array<'ACTIVE' | 'DISABLED'> | null;
    };
    url: '/user/page';
};

export type GetUserPageResponses = {
    /**
     * Standard paginated response envelope
     */
    200: {
        /**
         * List of items for the current page
         */
        items: Array<UserProfileResponseSchema>;
        meta: PaginationMetaSchema;
    };
};

export type GetUserPageResponse = GetUserPageResponses[keyof GetUserPageResponses];

export type PostUserData = {
    body: {
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Password for the user
         */
        password: string;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
    };
    path?: never;
    query?: never;
    url: '/user';
};

export type PostUserResponses = {
    /**
     * User created successfully
     */
    201: {
        /**
         * Unique identifier for the user
         */
        id: string;
        /**
         * Unique username for the user
         */
        username: string;
        /**
         * Role names assigned to the user
         */
        roles: Array<string>;
        /**
         * Email address of the user
         */
        email: string | null;
        /**
         * Phone number of the user
         */
        phone: string | null;
        /**
         * Display name of the user
         */
        displayName: string | null;
        /**
         * Timestamp when the user was created
         */
        createdAt: Date;
        /**
         * Timestamp when the user was last updated
         */
        updatedAt: Date;
    };
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type GetUserByIdResponses = {
    /**
     * User detail retrieved successfully
     */
    200: UserProfileResponseSchema;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type PutUserByIdData = {
    body: {
        /**
         * Unique username for the user
         */
        username?: string;
        /**
         * Email address of the user
         */
        email?: string | null;
        /**
         * Phone number of the user
         */
        phone?: string | null;
        /**
         * Display name of the user
         */
        displayName?: string | null;
        /**
         * Status of the user account
         */
        status?: 'ACTIVE' | 'DISABLED';
        /**
         * Role names assigned to the user
         */
        roles?: Array<string>;
    };
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type PutUserByIdResponses = {
    /**
     * User updated successfully
     */
    200: UserProfileResponseSchema;
};

export type PutUserByIdResponse = PutUserByIdResponses[keyof PutUserByIdResponses];

export type DeleteUserBatchData = {
    body: {
        /**
         * IDs of users to delete
         */
        userIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/user/batch';
};

export type DeleteUserBatchResponses = {
    /**
     * Users deleted successfully
     */
    200: {
        /**
         * Number of users deleted
         */
        deletedCount: number;
    };
};

export type DeleteUserBatchResponse = DeleteUserBatchResponses[keyof DeleteUserBatchResponses];

export type PatchUserStatusBatchData = {
    body: {
        /**
         * IDs of users to update status
         */
        userIds: Array<string>;
        /**
         * Target status for users
         */
        status: 'ACTIVE' | 'DISABLED';
    };
    path?: never;
    query?: never;
    url: '/user/status/batch';
};

export type PatchUserStatusBatchResponses = {
    /**
     * User status updated successfully
     */
    200: {
        /**
         * Number of users updated
         */
        updatedCount: number;
    };
};

export type PatchUserStatusBatchResponse = PatchUserStatusBatchResponses[keyof PatchUserStatusBatchResponses];
