// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Standard error response envelope
 */
export const zErrorResponse = z.object({
    code: z.string().optional(),
    message: z.string(),
    requestId: z.string()
}).describe('Standard error response envelope');

export const zAuthMenuSchema: z.AnyZodObject = z.object({
    id: z.string().describe('Menu ID'),
    name: z.string().describe('Menu name'),
    children: z.array(z.lazy(() => zAuthMenuSchema)).describe('Child menus'),
    actions: z.array(z.object({
        id: z.string().describe('Action ID'),
        name: z.string().describe('Action name')
    })).describe('Menu actions')
});

export const zGetAuthPrefillData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Prefilled credentials retrieved successfully
 */
export const zGetAuthPrefillResponse = z.object({
    username: z.string().describe('Prefilled username for login form'),
    password: z.string().describe('Prefilled password for login form')
}).describe('Prefilled credentials retrieved successfully');

export const zPostAuthLoginData = z.object({
    body: z.object({
        username: z.string().min(1).max(50).describe('Username of the user'),
        password: z.string().min(1).describe('Password of the user')
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User logged in successfully
 */
export const zPostAuthLoginResponse = z.object({
    accessToken: z.string().describe('Access token for the user'),
    refreshToken: z.string().describe('Refresh token for the user'),
    refreshTokenExpiresAt: z.string().datetime().describe('Refresh token expiry duration')
}).describe('User logged in successfully');

export const zPostAuthRefreshData = z.object({
    body: z.object({
        refreshToken: z.union([
            z.string(),
            z.null()
        ])
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Token refreshed successfully
 */
export const zPostAuthRefreshResponse = z.object({
    accessToken: z.string().describe('New access token'),
    refreshToken: z.string().describe('Rotated refresh token'),
    refreshTokenExpiresAt: z.string().datetime().describe('New refresh token expiry duration')
}).describe('Token refreshed successfully');

export const zPostAuthLogoutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User logged out successfully
 */
export const zPostAuthLogoutResponse = z.record(z.unknown()).describe('User logged out successfully');

export const zGetAuthMenusData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of menus accessible to the user
 */
export const zGetAuthMenusResponse = z.array(zAuthMenuSchema).describe('List of menus accessible to the user');

export const zPostUserData = z.object({
    body: z.object({
        username: z.string().min(3).max(30).describe('Unique username for the user'),
        password: z.string().min(6).max(100).describe('Password for the user'),
        email: z.union([
            z.string().email(),
            z.null()
        ]),
        phone: z.union([
            z.string().min(10).max(15),
            z.null()
        ]),
        displayName: z.union([
            z.string().max(50),
            z.null()
        ])
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User created successfully
 */
export const zPostUserResponse = z.object({
    id: z.string().describe('Unique identifier for the user'),
    username: z.string().describe('Unique username for the user'),
    email: z.union([
        z.string().email(),
        z.null()
    ]),
    phone: z.union([
        z.string(),
        z.null()
    ]),
    displayName: z.union([
        z.string(),
        z.null()
    ]),
    createdAt: z.string().datetime().describe('Timestamp when the user was created'),
    updatedAt: z.string().datetime().describe('Timestamp when the user was last updated')
}).describe('User created successfully');

export const zGetUserProfileData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User profile retrieved successfully
 */
export const zGetUserProfileResponse = z.object({
    id: z.string().describe('Unique identifier for the user'),
    username: z.string().describe('Unique username for the user'),
    email: z.union([
        z.string().email(),
        z.null()
    ]),
    phone: z.union([
        z.string(),
        z.null()
    ]),
    displayName: z.union([
        z.string(),
        z.null()
    ]),
    status: z.enum(['ACTIVE', 'DISABLED']).describe('Status of the user account'),
    createdAt: z.string().datetime().describe('Timestamp when the user was created'),
    updatedAt: z.string().datetime().describe('Timestamp when the user was last updated')
}).describe('User profile retrieved successfully');
