// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Standard error response envelope
 */
export const zErrorResponse = z.object({
    code: z.string().optional(),
    message: z.string(),
    requestId: z.string()
}).describe('Standard error response envelope');

export const zAuthActionSchema = z.object({
    id: z.string().describe('Action ID'),
    name: z.string().describe('Action name')
});

export const zAuthMenuSchema: z.AnyZodObject = z.object({
    id: z.string().describe('Menu ID'),
    name: z.string().describe('Menu name'),
    path: z.union([
        z.string(),
        z.null()
    ]),
    children: z.array(z.lazy(() => zAuthMenuSchema)).describe('Child menus'),
    actions: z.array(zAuthActionSchema).describe('Menu actions')
});

export const zRoleProfileResponseSchema = z.object({
    id: z.string().describe('Unique identifier for the role'),
    name: z.string().describe('Unique role name'),
    description: z.union([
        z.string(),
        z.null()
    ])
});

export const zRoleListResponseSchema = z.array(zRoleProfileResponseSchema);

export const zUserProfileResponseSchema = z.object({
    id: z.string().describe('Unique identifier for the user'),
    username: z.string().describe('Unique username for the user'),
    email: z.union([
        z.string().email(),
        z.null()
    ]),
    phone: z.union([
        z.string(),
        z.null()
    ]),
    displayName: z.union([
        z.string(),
        z.null()
    ]),
    status: z.enum(['ACTIVE', 'DISABLED']).describe('Status of the user account'),
    createdAt: z.string().datetime().describe('Timestamp when the user was created'),
    updatedAt: z.string().datetime().describe('Timestamp when the user was last updated')
});

export const zPaginationMetaSchema = z.object({
    totalItem: z.number().int().describe('Total number of items'),
    totalPage: z.number().int().describe('Total number of pages'),
    page: z.number().int().describe('Current page number'),
    pageSize: z.number().int().describe('Number of items per page'),
    nextPage: z.union([
        z.number().int(),
        z.null()
    ]),
    previousPage: z.union([
        z.number().int(),
        z.null()
    ]),
    hasNext: z.boolean().describe('Indicates if there is a next page'),
    hasPrevious: z.boolean().describe('Indicates if there is a previous page'),
    sort: z.union([
        z.string(),
        z.null()
    ])
});

export const zGetAuthPrefillData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Prefilled credentials retrieved successfully
 */
export const zGetAuthPrefillResponse = z.object({
    username: z.string().describe('Prefilled username for login form'),
    password: z.string().describe('Prefilled password for login form')
}).describe('Prefilled credentials retrieved successfully');

export const zPostAuthLoginData = z.object({
    body: z.object({
        username: z.string().min(1).max(50).describe('Username of the user'),
        password: z.string().min(1).describe('Password of the user')
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User logged in successfully
 */
export const zPostAuthLoginResponse = z.object({
    accessToken: z.string().describe('Access token for the user'),
    refreshToken: z.string().describe('Refresh token for the user'),
    refreshTokenExpiresAt: z.string().datetime().describe('Refresh token expiry duration')
}).describe('User logged in successfully');

export const zPostAuthRefreshData = z.object({
    body: z.object({
        refreshToken: z.union([
            z.string(),
            z.null()
        ])
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Token refreshed successfully
 */
export const zPostAuthRefreshResponse = z.object({
    accessToken: z.string().describe('New access token'),
    refreshToken: z.string().describe('Rotated refresh token'),
    refreshTokenExpiresAt: z.string().datetime().describe('New refresh token expiry duration')
}).describe('Token refreshed successfully');

export const zPostAuthLogoutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User logged out successfully
 */
export const zPostAuthLogoutResponse = z.record(z.unknown()).describe('User logged out successfully');

export const zGetAuthMenusData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of menus accessible to the user
 */
export const zGetAuthMenusResponse = z.array(zAuthMenuSchema).describe('List of menus accessible to the user');

export const zGetRoleData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Role list retrieved successfully
 */
export const zGetRoleResponse = zRoleListResponseSchema;

export const zPostRoleData = z.object({
    body: z.object({
        name: z.string().min(1).max(50).describe('Unique role name'),
        description: z.union([
            z.string().max(255),
            z.null()
        ])
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Role created successfully
 */
export const zPostRoleResponse = z.object({
    id: z.string().describe('Unique identifier for the role'),
    name: z.string().describe('Unique role name'),
    description: z.union([
        z.string(),
        z.null()
    ])
}).describe('Role created successfully');

export const zDeleteRoleByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().describe('Role ID')
    }),
    query: z.never().optional()
});

/**
 * Role deleted successfully
 */
export const zDeleteRoleByIdResponse = z.object({
    deletedCount: z.number().int().gte(0).describe('Number of roles deleted')
}).describe('Role deleted successfully');

export const zGetRoleByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().describe('Role ID')
    }),
    query: z.never().optional()
});

/**
 * Role detail retrieved successfully
 */
export const zGetRoleByIdResponse = zRoleProfileResponseSchema;

export const zPutRoleByIdData = z.object({
    body: z.object({
        name: z.string().min(1).max(50).describe('Unique role name').optional(),
        description: z.union([
            z.string().max(255),
            z.null()
        ]).optional()
    }),
    path: z.object({
        id: z.string().describe('Role ID')
    }),
    query: z.never().optional()
});

/**
 * Role updated successfully
 */
export const zPutRoleByIdResponse = zRoleProfileResponseSchema;

export const zGetUserProfileData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User profile retrieved successfully
 */
export const zGetUserProfileResponse = zUserProfileResponseSchema;

export const zGetUserPageData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().int().gte(1).describe('Page number for pagination'),
        pageSize: z.number().int().gte(1).lte(100).describe('Number of items per page'),
        sort: z.union([
            z.string(),
            z.null()
        ]).optional().default(null),
        search: z.union([
            z.string().max(100),
            z.null()
        ]).optional().default(null),
        status: z.union([
            z.array(z.enum(['ACTIVE', 'DISABLED'])),
            z.null()
        ]).optional().default(null)
    })
});

/**
 * Standard paginated response envelope
 */
export const zGetUserPageResponse = z.object({
    items: z.array(zUserProfileResponseSchema).describe('List of items for the current page'),
    meta: zPaginationMetaSchema
}).describe('Standard paginated response envelope');

export const zPostUserData = z.object({
    body: z.object({
        username: z.string().min(3).max(30).describe('Unique username for the user'),
        password: z.string().min(6).max(100).describe('Password for the user'),
        email: z.union([
            z.string().email(),
            z.null()
        ]),
        phone: z.union([
            z.string().min(10).max(15),
            z.null()
        ]),
        displayName: z.union([
            z.string().max(50),
            z.null()
        ])
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User created successfully
 */
export const zPostUserResponse = z.object({
    id: z.string().describe('Unique identifier for the user'),
    username: z.string().describe('Unique username for the user'),
    email: z.union([
        z.string().email(),
        z.null()
    ]),
    phone: z.union([
        z.string(),
        z.null()
    ]),
    displayName: z.union([
        z.string(),
        z.null()
    ]),
    createdAt: z.string().datetime().describe('Timestamp when the user was created'),
    updatedAt: z.string().datetime().describe('Timestamp when the user was last updated')
}).describe('User created successfully');

export const zGetUserByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().describe('User ID')
    }),
    query: z.never().optional()
});

/**
 * User detail retrieved successfully
 */
export const zGetUserByIdResponse = zUserProfileResponseSchema;

export const zPutUserByIdData = z.object({
    body: z.object({
        username: z.string().min(3).max(30).describe('Unique username for the user').optional(),
        email: z.union([
            z.string().email(),
            z.null()
        ]).optional(),
        phone: z.union([
            z.string().min(10).max(15),
            z.null()
        ]).optional(),
        displayName: z.union([
            z.string().max(50),
            z.null()
        ]).optional(),
        status: z.enum(['ACTIVE', 'DISABLED']).describe('Status of the user account').optional()
    }),
    path: z.object({
        id: z.string().describe('User ID')
    }),
    query: z.never().optional()
});

/**
 * User updated successfully
 */
export const zPutUserByIdResponse = zUserProfileResponseSchema;

export const zDeleteUserBatchData = z.object({
    body: z.object({
        userIds: z.array(z.string()).min(1).describe('IDs of users to delete')
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Users deleted successfully
 */
export const zDeleteUserBatchResponse = z.object({
    deletedCount: z.number().int().gte(0).describe('Number of users deleted')
}).describe('Users deleted successfully');

export const zPatchUserStatusBatchData = z.object({
    body: z.object({
        userIds: z.array(z.string()).min(1).describe('IDs of users to update status'),
        status: z.enum(['ACTIVE', 'DISABLED']).describe('Target status for users')
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User status updated successfully
 */
export const zPatchUserStatusBatchResponse = z.object({
    updatedCount: z.number().int().gte(0).describe('Number of users updated')
}).describe('User status updated successfully');
